"""Adiciona controle de parcelas

Revision ID: ecb24cddabb6
Revises: 
Create Date: 2025-01-19 12:30:19.740726

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ecb24cddabb6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pedido', schema=None) as batch_op:
        batch_op.add_column(sa.Column('primeira_parcela_paga', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('segunda_parcela_paga', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('data_primeira_parcela', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('data_segunda_parcela', sa.DateTime(), nullable=True))
        batch_op.alter_column('modelo_camisa',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=20),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pedido', schema=None) as batch_op:
        batch_op.alter_column('modelo_camisa',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
        batch_op.drop_column('data_segunda_parcela')
        batch_op.drop_column('data_primeira_parcela')
        batch_op.drop_column('segunda_parcela_paga')
        batch_op.drop_column('primeira_parcela_paga')

    # ### end Alembic commands ###
